### ISSUE TITLE
Snyk Reported issue with @okta/jwt-verifier@3.0.0 > njwt@2.0.0 

### ISSUE THREAD

**Issue by RGanni49** [jwtk/njwt#106]
the package @okta/jwt-verifier@3.0.0  is having njwt@2.0.0  as a dependency\

https://www.npmjs.com/package/@okta/jwt-verifier?activeTab=dependencies

snyk has reported an issue with njwt@2.0.0

https://security.snyk.io/vuln/SNYK-JS-NJWT-6861582.

please check the attached image to view the issue reported by snyk.
<img width="592" alt="synk-okta-issue" src="https://github.com/jwtk/njwt/assets/120459432/0e4537e0-a1c2-475a-b564-d2f2007cff5f">

is there an update that can resolve the issue  for okta/jwt-verifier

**Comment by dansternfeld1** [comment]
Looks like @jaredperreault-okta is addressing this in #107 
Thank you, Jared!

**Comment by bdelongamfam** [comment]
This is good because it's about 6 days from breaching the 30 day High SLA at my org but without a fix we can't patch.

Thanks @jaredperreault-okta !

**Comment by nattap0l** [comment]
Hi i found error when start application

njwt@2.0.1 is new version update i found error this below from @okta/jwt-verifier@3.0.1

/var/www/engine/project/node_modules/@okta/jwt-verifier/lib.js:241 
jwt[methodName] = method.bind({ body: jwtBodyProxy })
TypeError: Cannot assign to read only property 'setClaim' of object '[object Object]'
at /var/www/engine/project/node_modules/@okta/jwt-verifier/lib.js:241:29

Node.js v18.x.x

@dansternfeld1

**Comment by dansternfeld1** [comment]
> Hi i found error when start application
> 
> njwt@2.0.1 is new version update i found error this below from @okta/jwt-verifier@3.0.1
> 
> /var/www/engine/project/node_modules/@okta/jwt-verifier/lib.js:241  jwt[methodName] = method.bind({ body: jwtBodyProxy }) TypeError: Cannot assign to read only property 'setClaim' of object '[object Object]' at /var/www/engine/project/node_modules/@okta/jwt-verifier/lib.js:241:29
> 
> Node.js v18.x.x
> 
> @dansternfeld1

cc @jaredperreault-okta -- see above

**Comment by jaredperreault-okta** [comment]
@nattap0l This has been addressed in `@okta/jwt-verifier` package directly in version `3.2.1`. `3.2.2` was also just released, which includes a fix for the CVE
